import XCTest
@testable import osrswiki

@MainActor
final class StaticSettingsPreviewSourceGuardTest: XCTestCase {
    func testNormalSettingsPreviewUiDoesNotInvokeDynamicPreviewGeneration() throws {
        let root = try repositoryRoot()

        let mainTab = try source(root, "platforms/ios/osrswiki/Views/MainTabView.swift")
        let customMainTab = try source(root, "platforms/ios/osrswiki/Views/CustomMainTabView.swift")
        let appearance = try source(root, "platforms/ios/osrswiki/Views/Settings/AppearanceSettingsView.swift")

        XCTAssertFalse(mainTab.contains("preGenerateAllPreviews"))
        XCTAssertFalse(customMainTab.contains("preGenerateAllPreviews"))
        XCTAssertFalse(appearance.contains("osrsBackgroundPreviewManager.shared"))
        XCTAssertFalse(appearance.contains("generatePreview(for:"))
        XCTAssertFalse(appearance.contains("generateTablePreview("))
        XCTAssertFalse(appearance.contains("osrsThemePreviewCard"))
        XCTAssertFalse(appearance.contains("osrsTablePreviewCard"))
        XCTAssertFalse(appearance.contains("osrsStaticSettingsPreviewAssets"))
        XCTAssertTrue(appearance.contains("appearance_theme_picker"))
        XCTAssertTrue(appearance.contains("Text(\"Display\")"))
        XCTAssertTrue(appearance.contains("appearance_collapse_tables_toggle"))
        XCTAssertTrue(appearance.contains("appearance_wrap_table_cells_toggle"))
        XCTAssertTrue(appearance.contains("appearance_article_text_scale"))
        XCTAssertTrue(appearance.contains("appearance_swipe_right_back_toggle"))
        XCTAssertTrue(appearance.contains("appearance_swipe_left_contents_toggle"))
    }

    func testReaderPreferencesPersistClampAndKeepLegacyDefaults() throws {
        let suiteName = "StaticSettingsPreviewSourceGuardTest.\(UUID().uuidString)"
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suiteName))
        defer { defaults.removePersistentDomain(forName: suiteName) }

        let initial = osrsThemeManager(userDefaults: defaults)
        XCTAssertEqual(initial.articleTextScale, 1.0)
        XCTAssertTrue(initial.swipeRightToGoBackEnabled)
        XCTAssertTrue(initial.swipeLeftToShowContentsEnabled)
        XCTAssertFalse(initial.collapseTables)
        XCTAssertFalse(initial.wrapTableCells)

        initial.setArticleTextScale(1.25)
        initial.setSwipeRightToGoBackEnabled(false)
        initial.setSwipeLeftToShowContentsEnabled(false)
        initial.setCollapseTables(false)
        initial.setWrapTableCells(true)
        initial.setTheme(.osrsDark)
        XCTAssertTrue(initial.currentTheme is osrsDarkTheme)

        let reloaded = osrsThemeManager(userDefaults: defaults)
        XCTAssertEqual(reloaded.articleTextScale, 1.25, accuracy: 0.001)
        XCTAssertFalse(reloaded.swipeRightToGoBackEnabled)
        XCTAssertFalse(reloaded.swipeLeftToShowContentsEnabled)
        XCTAssertFalse(reloaded.collapseTables)
        XCTAssertTrue(reloaded.wrapTableCells)
        XCTAssertEqual(reloaded.selectedTheme, .osrsDark)
        XCTAssertTrue(reloaded.currentTheme is osrsDarkTheme)

        reloaded.setTheme(.osrsLight)
        XCTAssertTrue(reloaded.currentTheme is osrsLightTheme)

        reloaded.setArticleTextScale(9.0)
        XCTAssertEqual(reloaded.articleTextScale, 1.40, accuracy: 0.001)
        reloaded.setArticleTextScale(0.1)
        XCTAssertEqual(reloaded.articleTextScale, 0.85, accuracy: 0.001)
    }

    func testIOS26RootAndArticleChromeAreAvailabilityGated() throws {
        let root = try repositoryRoot()
        let customMain = try source(root, "platforms/ios/osrswiki/Views/CustomMainTabView.swift")
        let article = try source(root, "platforms/ios/osrswiki/Views/ArticleView.swift")
        let articleWebView = try source(root, "platforms/ios/osrswiki/Views/ArticleWebView.swift")
        let app = try source(root, "platforms/ios/osrswiki/osrswikiApp.swift")
        let tabItem = try source(root, "platforms/ios/osrswiki/Models/TabItem.swift")
        let legacyTabBar = try source(root, "platforms/ios/osrswiki/Views/Components/CustomTabBar.swift")

        XCTAssertTrue(customMain.contains("if #available(iOS 26.0, *)"))
        XCTAssertTrue(customMain.contains("TabView(selection: nativeTabSelection)"))
        XCTAssertTrue(customMain.contains(".tabBarMinimizeBehavior(.never)"))
        XCTAssertTrue(customMain.contains(".overlay {"))
        XCTAssertTrue(customMain.contains("articleBottomBar"))
        XCTAssertTrue(customMain.contains(".preferredColorScheme(themeManager.selectedTheme.colorScheme)"))
        XCTAssertFalse(customMain.contains(".preferredColorScheme(themeManager.currentColorScheme)"))
        for identifier in ["home_tab", "saved_tab", "search_tab", "map_tab", "more_tab"] {
            XCTAssertTrue(tabItem.contains("\"\(identifier)\""), "Missing stable root tab \(identifier)")
        }
        XCTAssertTrue(customMain.contains(".accessibilityIdentifier(item.accessibilityIdentifier)"))
        XCTAssertTrue(legacyTabBar.contains(".accessibilityIdentifier(item.accessibilityIdentifier)"))
        XCTAssertTrue(customMain.contains("osrsTestEnvironment.isRunningSimulatorUITestHarness"))
        XCTAssertTrue(customMain.contains("#if DEBUG"))
        XCTAssertTrue(customMain.contains("ColorExtractor.exportColorsToJSON"))
        XCTAssertTrue(article.contains(".overlay(alignment: .top)") || article.contains("osrsPairedEdgeChrome(edge: .top)"))
        XCTAssertTrue(article.contains(".ignoresSafeArea()"))
        XCTAssertFalse(article.contains(".safeAreaBar(edge: .top"))
        XCTAssertTrue(article.contains("osrsPairedEdgeChrome(edge: .top)"))
        XCTAssertTrue(customMain.contains("osrsOverlayChromeMetrics.screenEdgeGap"))
        XCTAssertTrue(customMain.contains(".ignoresSafeArea(edges: .bottom)"))
        let chromeHelper = try source(root, "platforms/ios/osrswiki/Utils/osrsVoiceSearchAnimationHelper.swift")
        XCTAssertTrue(chromeHelper.contains("osrsOverlayChromeMetrics.pairedEdgeGap"))
        XCTAssertTrue(chromeHelper.contains("func osrsPairedEdgeChrome"))
        XCTAssertTrue(chromeHelper.contains("static func pillShape(height: CGFloat) -> RoundedRectangle"))
        XCTAssertTrue(chromeHelper.contains("style: .circular"))
        XCTAssertTrue(chromeHelper.contains("osrsFloatingGlass(in: osrsSearchControlGeometry.pillShape"))
        XCTAssertTrue(chromeHelper.contains(".containerShape(shape)"))
        XCTAssertTrue(chromeHelper.contains(".clipShape(shape)"))
        XCTAssertFalse(chromeHelper.contains("RoundedRectangle(cornerRadius: 18"))
        XCTAssertTrue(articleWebView.contains("osrsArticleWebKitRuntime.processPool"))
        let warmer = try source(root, "platforms/ios/osrswiki/Services/osrsWebViewProcessWarmer.swift")
        XCTAssertTrue(warmer.contains("osrsArticleWebKitRuntime.processPool"))
        XCTAssertFalse(warmer.contains(".nonPersistent()"))
        let more = try source(root, "platforms/ios/osrswiki/Views/MoreView.swift")
        XCTAssertTrue(more.contains(".navigationBarHidden(true)"))
        XCTAssertFalse(more.contains(".navigationTitle(\"More\")"))

        let articleSearch = try source(root, "platforms/ios/osrswiki/Views/Components/osrsArticleSearchBar.swift")
        XCTAssertTrue(articleSearch.contains("let searchHeight = controlHeight"))
        XCTAssertFalse(articleSearch.contains("min(36 * scale, 52)"))
        XCTAssertTrue(articleSearch.contains(".padding(.vertical, 0)"))
        XCTAssertTrue(articleSearch.contains(".frame(width: 80, alignment: .center)"))
        XCTAssertTrue(articleSearch.contains("osrsSearchControlGeometry.pillShape"))
        let bottomBar = try source(root, "platforms/ios/osrswiki/Views/Components/osrsArticleBottomBar.swift")
        XCTAssertTrue(bottomBar.contains("osrsOverlayChromeMetrics.floatingBarHeight"))
        XCTAssertTrue(bottomBar.contains("Capsule()"))
        XCTAssertFalse(bottomBar.contains("osrsOverlayChromeMetrics.bottomInset"))
        XCTAssertTrue(bottomBar.contains("osrsFloatingGlass"))
        XCTAssertTrue(articleWebView.contains("osrsPreparedArticleWebViewStore.shared.take"))
        XCTAssertTrue(articleWebView.contains("collapseTablesEnabled: themeManager.collapseTables"))
        XCTAssertFalse(articleWebView.contains("collapseTablesEnabled: viewModel.collapseTablesEnabled"))
        XCTAssertTrue(articleWebView.contains("osrsArticleRefreshSettlement.configure"))
        let refreshSettlement = try source(root, "platforms/ios/osrswiki/Utils/osrsArticleRefreshSettlement.swift")
        XCTAssertTrue(refreshSettlement.contains("scrollView.contentInset.bottom = 0"))
        XCTAssertTrue(app.contains("enum osrsAppRoot"))
        let liveTheme = try source(root, "platforms/ios/osrswiki/Models/osrsLiveThemeApplier.swift")
        XCTAssertTrue(liveTheme.contains("if #available(iOS 26.0, *)"))
        XCTAssertTrue(liveTheme.contains("apply(theme, toView:"))
        XCTAssertTrue(liveTheme.contains("UISwitch"))

        let htmlBuilder = try source(root, "platforms/ios/osrswiki/Services/osrsPageHtmlBuilder.swift")
        XCTAssertTrue(htmlBuilder.contains("web/collapsible_tables.css"))
        XCTAssertTrue(htmlBuilder.contains("styles/ios-article-aesthetics.css"))
        XCTAssertTrue(htmlBuilder.contains("viewport-fit=cover"))
        XCTAssertTrue(htmlBuilder.contains("--osrs-article-chrome-clearance"))
        XCTAssertTrue(htmlBuilder.contains("osrsSearchControlGeometry.compactHeight"))
        XCTAssertFalse(
            htmlBuilder.contains("body {\n                padding-top: calc"),
            "Reader preferences must not re-pad body; html already owns chrome clearance."
        )
        XCTAssertTrue(htmlBuilder.contains("__osrsAmdDefine"))

        let map = try source(root, "platforms/ios/osrswiki/Views/OSRSMapLibreView.swift")
        XCTAssertTrue(map.contains(".ignoresSafeArea()"))
        XCTAssertTrue(map.contains("osrsMapGlassChrome(in: Capsule())"))
        XCTAssertTrue(map.contains("osrsMapGlassChrome(in: Circle())"))
        XCTAssertTrue(map.contains("location.north.fill"))
        XCTAssertTrue(map.contains("osrsRealmFloorControl(store: store, realm: realm)"))
        XCTAssertTrue(map.contains("osrsOverlayChromeMetrics.mapFloatingControlBottomInset"))
        XCTAssertTrue(map.contains("osrsFloatingGlass"))
        XCTAssertFalse(map.contains("theme is osrsLightTheme"))
        XCTAssertTrue(map.contains("osrsMapGlassChrome(in: osrsSearchControlGeometry.pillShape"))
        XCTAssertTrue(map.contains("osrsMapPreferredFrameRate.apply(to: mapView)"))
        XCTAssertTrue(map.contains("osrsMapPreferredFrameRate.viewRange"))
        XCTAssertFalse(map.contains("osrsMapGlassChrome(in: RoundedRectangle(cornerRadius: 16"))
        XCTAssertTrue(map.contains("applyNorthCamera"))
        XCTAssertTrue(map.contains("holdCompassReset"))
        XCTAssertFalse(map.contains(".ignoresSafeArea(.container, edges: .top)"))

        let coordinator = try source(root, "platforms/ios/osrswiki/Services/osrsArticleDocumentCoordinator.swift")
        XCTAssertTrue(coordinator.contains("osrsPreparedArticleWebViewStore.shared.preload"))
        XCTAssertTrue(articleWebView.contains("canonicalAssetPath"))

        let toc = try source(root, "platforms/ios/osrswiki/Views/Components/osrsContentsDrawerSimple.swift")
        XCTAssertTrue(toc.contains("osrsFloatingGlass"))
        XCTAssertTrue(toc.contains("osrs-contents-drawer-panel"))
        XCTAssertTrue(toc.contains("RoundedRectangle(cornerRadius: 28, style: .continuous)"))
        XCTAssertTrue(toc.contains("simultaneousGesture(dismissDrag)"))
        XCTAssertTrue(toc.contains("suppressSectionSelection"))
        XCTAssertTrue(toc.contains("isDismissTracking = false"))
        XCTAssertTrue(toc.contains("osrsContentsReveal.isVisuallyOpen"))
        XCTAssertTrue(toc.contains("scrollDisabled(isDismissTracking)"))
        XCTAssertTrue(toc.contains("osrsInteractiveArticleSwipe.contentsParkedOffset"))
        XCTAssertTrue(toc.contains(".clipped()"))
        XCTAssertTrue(toc.contains("revealProgress <= 0 ? 0 : 1"))
        XCTAssertFalse(toc.contains("LazyVStack"))
        XCTAssertFalse(toc.contains(".background(osrsTheme.surface)"))
        XCTAssertFalse(toc.contains(".background(fallback, in: shape)"))

        let nativeMap = try source(root, "platforms/ios/osrswiki/Services/osrsNativeMapHandler.swift")
        XCTAssertTrue(nativeMap.contains("osrsMapPreferredFrameRate.apply(to: mapView)"))
        let preloader = try source(root, "platforms/ios/osrswiki/Services/osrsBackgroundMapPreloader.swift")
        XCTAssertTrue(preloader.contains("osrsMapPreferredFrameRate.apply(to: mapView)"))
        let preload = try source(root, "platforms/ios/osrswiki/Services/osrsMapPreloadService.swift")
        XCTAssertTrue(preload.contains("osrsMapPreferredFrameRate.apply(to: mapView)"))
        let prewarm = try source(root, "platforms/ios/osrswiki/Services/osrsMapTilePrewarmingService.swift")
        XCTAssertTrue(prewarm.contains("osrsMapPreferredFrameRate.apply(to: mapView)"))
        let frameRate = try source(root, "platforms/ios/osrswiki/Utils/osrsMapPreferredFrameRate.swift")
        XCTAssertTrue(frameRate.contains("CADisableMinimumFrameDurationOnPhone"))
        XCTAssertTrue(frameRate.contains("mapView.preferredFramesPerSecond = framesPerSecond"))
        XCTAssertFalse(frameRate.contains("view.preferredFrameRateRange"))

        let sharedFixes = try source(root, "shared/css/fixes.css")
        XCTAssertTrue(sharedFixes.contains("--osrs-disclosure-content-inline-inset: 12px;"))
        XCTAssertTrue(sharedFixes.contains("--osrs-disclosure-content-block-inset: 8px;"))
        XCTAssertTrue(sharedFixes.contains("--osrs-disclosure-nested-well-bg: var(--body-main);"))
        XCTAssertTrue(sharedFixes.contains("Nested-in-collapsible wells"))
        XCTAssertTrue(sharedFixes.contains("background-color: var(--osrs-disclosure-nested-well-bg, var(--body-main)) !important;"))
        XCTAssertTrue(sharedFixes.contains(".collapsible-container .collapsible-container {"))
        XCTAssertTrue(sharedFixes.contains(".collapsible-container .collapsible-container .collapsible-container {"))
        XCTAssertTrue(sharedFixes.contains(".collapsible-container .osrs-calculator-result"))
        XCTAssertTrue(sharedFixes.contains(":has(> .collapsible-content .collapsible-container)"))
        XCTAssertTrue(sharedFixes.contains(":has(> .collapsible-content .osrs-calculator-result)"))
        XCTAssertTrue(sharedFixes.contains(".osrs-disclosure-body"))
        XCTAssertTrue(sharedFixes.contains("margin-inline: var(--osrs-disclosure-content-inline-inset) !important;"))
        XCTAssertTrue(sharedFixes.contains("width: auto !important;"))
        XCTAssertTrue(sharedFixes.contains("display: flow-root !important;"))
        XCTAssertTrue(sharedFixes.contains("float: none !important;"))
        XCTAssertTrue(sharedFixes.contains("background-color: var(--osrs-disclosure-chrome-bg, var(--body-mid)) !important;"))
        XCTAssertTrue(sharedFixes.contains(".collapsible-infobox:not(.collapsed) > .collapsible-content"))
        XCTAssertTrue(sharedFixes.contains("padding-inline: var(--osrs-disclosure-content-inline-inset) !important;"))
        let disclosureStart = try XCTUnwrap(sharedFixes.range(of: ".collapsible-container:not(.collapsed) > .collapsible-content > .osrs-disclosure-body,"))
        let nestedWellMark = try XCTUnwrap(sharedFixes.range(of: "/* Nested-in-collapsible wells"))
        let disclosureBodyRule = String(sharedFixes[disclosureStart.lowerBound..<nestedWellMark.lowerBound])
        XCTAssertTrue(disclosureBodyRule.contains("padding-inline: 0 !important;"))
        XCTAssertFalse(disclosureBodyRule.contains("padding-inline: var(--osrs-disclosure-content-inline-inset)"))
        let sharedThemes = try source(root, "shared/css/themes.css")
        XCTAssertTrue(sharedThemes.contains("--osrs-disclosure-chrome-bg: var(--body-light);"))
        XCTAssertFalse(sharedThemes.contains("color-mix(in srgb, var(--body-main) 78%, var(--body-light) 22%)"))
        let iosTables = try source(root, "platforms/ios/osrswiki/Assets/web/collapsible_tables.css")
        XCTAssertTrue(iosTables.contains(":not(.collapsible-infobox):not(.collapsible-primary-infobox)"))
        let iosAesthetics = try source(root, "platforms/ios/osrswiki/Assets/styles/ios-article-aesthetics.css")
        XCTAssertTrue(iosAesthetics.contains("scrollbar-gutter: auto !important;"))
        XCTAssertTrue(iosAesthetics.contains("margin-inline: var(--osrs-disclosure-content-inline-inset, 12px) !important;"))
        XCTAssertTrue(iosAesthetics.contains("display: flow-root !important;"))
        XCTAssertTrue(iosAesthetics.contains("background-color: var(--osrs-disclosure-chrome-bg, var(--body-mid)) !important;"))
        XCTAssertTrue(iosAesthetics.contains("Nested-in-collapsible wells"))
        XCTAssertTrue(iosAesthetics.contains("background-color: var(--osrs-disclosure-nested-well-bg, var(--body-main)) !important;"))
        XCTAssertTrue(iosAesthetics.contains(".collapsible-container .osrs-calculator-result"))
        XCTAssertTrue(iosAesthetics.contains(":has(> .collapsible-content .collapsible-container)"))
        XCTAssertTrue(iosAesthetics.contains(".collapsible-infobox:not(.collapsed) > .collapsible-content"))
        XCTAssertTrue(iosAesthetics.contains("max-width: min(18.75rem, 100%) !important;"))
        XCTAssertTrue(iosAesthetics.contains(":has(.mw-kartographer-map)"))
        XCTAssertTrue(iosAesthetics.contains("width: max-content !important;"))
        XCTAssertFalse(iosAesthetics.contains(".collapsible-primary-infobox > .collapsible-content,\n.collapsible-bonuses-infobox > .collapsible-content {\n    padding: 0 !important;"))
        let articleView = try source(root, "platforms/ios/osrswiki/Views/ArticleView.swift")
        XCTAssertTrue(articleView.contains("osrsContentsReveal.settleAnimation"))
        XCTAssertTrue(articleView.contains("contentsSettleGeneration"))
        XCTAssertTrue(articleView.contains("guard generation == contentsSettleGeneration"))
        XCTAssertTrue(articleView.contains("velocity: velocity"))
        let drawer = try source(root, "platforms/ios/osrswiki/Views/Components/osrsContentsDrawerSimple.swift")
        XCTAssertTrue(drawer.contains("settleGeneration"))
        XCTAssertTrue(drawer.contains("guard generation == settleGeneration"))
        let collapsible = try source(root, "shared/js/collapsible_content.js")
        XCTAssertTrue(collapsible.contains("appendDisclosureBody"))
        XCTAssertTrue(collapsible.contains("absorbDisclosureChildren"))
        XCTAssertTrue(collapsible.contains("applyDisclosureInnerInset"))
        XCTAssertTrue(collapsible.contains("scheduleDisclosureInnerInsets"))
        XCTAssertTrue(collapsible.contains("osrs-disclosure-inset-target"))
        XCTAssertTrue(collapsible.contains("osrs-disclosure-body"))
    }

    func testArticlePreferencesAreLiveAndDoNotMutateSharedAssets() throws {
        let root = try repositoryRoot()
        let appearance = try source(root, "platforms/ios/osrswiki/Views/Settings/AppearanceSettingsView.swift")
        let article = try source(root, "platforms/ios/osrswiki/Views/ArticleView.swift")
        let webView = try source(root, "platforms/ios/osrswiki/Views/ArticleWebView.swift")
        let builder = try source(root, "platforms/ios/osrswiki/Services/osrsPageHtmlBuilder.swift")

        XCTAssertTrue(appearance.contains("in: osrsThemeManager.articleTextScaleRange"))
        XCTAssertTrue(appearance.contains("osrsSettingsPage("))
        XCTAssertTrue(appearance.contains("usesLargeTitle"))
        XCTAssertTrue(appearance.contains("transaction { $0.animation = nil }"))
        XCTAssertTrue(appearance.contains("animation(nil, value: themeManager.floorNumberingMode)"))
        XCTAssertFalse(appearance.contains("osrsAppearancePreferenceLabel"))
        XCTAssertFalse(appearance.contains("frame(height: 36"))
        XCTAssertTrue(article.contains(".onChange(of: themeManager.articleTextScale)"))
        let settingsPage = try source(root, "platforms/ios/osrswiki/Views/Settings/osrsSettingsPage.swift")
        XCTAssertTrue(settingsPage.contains("osrsMoreDestinationChrome"))
        XCTAssertTrue(settingsPage.contains(".listStyle(.insetGrouped)"))
        let moreChrome = try source(root, "platforms/ios/osrswiki/Views/Components/osrsMoreDestinationChrome.swift")
        XCTAssertTrue(moreChrome.contains("osrsInteractiveBackSwipe()"))
        XCTAssertFalse(moreChrome.contains("toolbarBackground(Color(osrsTheme.background)"))
        XCTAssertTrue(article.contains("themeManager.swipeRightToGoBackEnabled ?"))
        XCTAssertTrue(article.contains("themeManager.swipeLeftToShowContentsEnabled ?"))
        XCTAssertTrue(webView.contains("context.coordinator.parent = self"))
        XCTAssertTrue(webView.contains("mapHandler?.ownsArticleGesture"))
        XCTAssertTrue(webView.contains("classifyArticleGestureStartPoint("))
        XCTAssertTrue(builder.contains("osrs-article-reader-preferences"))
        XCTAssertTrue(builder.contains("--osrs-article-user-text-scale"))
    }

    func testSettingsPreviewAssetsAreGeneratedFromSimulatorAppRendering() throws {
        let root = try repositoryRoot()

        let generator = try source(root, "tools/settings-preview-assets/generate-settings-preview-assets.swift")
        let iosScript = try source(root, "scripts/ios/generate-settings-preview-assets.sh")
        let generatorTest = try source(root, "platforms/ios/osrswikiTests/SettingsPreviewAssetGenerationTest.swift")
        let exportView = try source(root, "platforms/ios/osrswiki/Views/Settings/osrsSettingsPreviewExportView.swift")

        XCTAssertFalse(generator.contains("import AppKit"), "Preview generator must not use host-side AppKit drawing.")
        XCTAssertFalse(generator.contains("NSBezierPath"), "Preview generator must not hand-draw generic preview shapes.")
        XCTAssertFalse(generator.contains("drawThemePreview("), "Theme assets must come from app-rendered previews.")
        XCTAssertFalse(generator.contains("drawTablePreview("), "Table assets must come from app-rendered previews.")

        XCTAssertTrue(iosScript.contains("SettingsPreviewAssetGenerationTest"))
        XCTAssertTrue(iosScript.contains("simctl get_app_container"))
        XCTAssertTrue(iosScript.contains("simctl io"))
        XCTAssertTrue(iosScript.contains("-settingsPreviewExport"))
        XCTAssertTrue(generatorTest.contains("osrsThemePreviewRenderer.shared"))
        XCTAssertTrue(exportView.contains("WKWebView"))
        XCTAssertTrue(exportView.contains("osrsPageHtmlBuilder"))
        XCTAssertTrue(exportView.contains("settings_preview_capture_ready"))
    }

    private func repositoryRoot() throws -> URL {
        var url = URL(fileURLWithPath: #filePath)
        while url.pathComponents.count > 1 {
            if FileManager.default.fileExists(atPath: url.appendingPathComponent("AGENTS.md").path),
               FileManager.default.fileExists(atPath: url.appendingPathComponent("platforms/ios/osrswiki.xcodeproj").path) {
                return url
            }
            url.deleteLastPathComponent()
        }
        throw XCTSkip("Could not locate repository root from \(#filePath)")
    }

    private func source(_ root: URL, _ path: String) throws -> String {
        let fileURL = root.appendingPathComponent(path)
        return try String(contentsOf: fileURL, encoding: .utf8)
    }
}
