//
//  osrsMapDefaultView.swift
//  OSRS Wiki
//
//  Generated by scripts/shared/stamp-map-default-view.py from shared/map-default-view.json.
//

import CoreLocation

enum osrsMapDefaultView {
    static let gameX = 3222.0
    static let gameY = 3218.0
    static let plane = 0
    static let gameCoordScale = 4.0
    static let gameMinX = 960.0
    static let gameMaxX = 4224.0
    static let gameMinY = 1216.0
    static let gameMaxY = 12608.0
    static let sourceImageWidth = 13056.0
    static let sourceImageHeight = 45568.0
    static let tileSize = 1024.0
    static let maxZoom = 6
    static let canvasSize = 65536.0
    static let latitude = -25.44327461230575
    static let longitude = -130.2978515625
    static let zoom = 7.3414426741929

    static let coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    static var southWestCoordinate: CLLocationCoordinate2D { mapCoordinate(gameX: gameMinX, gameY: gameMinY) }
    static var northEastCoordinate: CLLocationCoordinate2D { mapCoordinate(gameX: gameMaxX, gameY: gameMaxY) }

    static func mapCoordinate(gameX: Double, gameY: Double) -> CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: latitudeForGameY(gameY), longitude: longitudeForGameX(gameX))
    }

    static func longitudeForGameX(_ gameX: Double) -> Double {
        let px = (gameX - gameMinX) * gameCoordScale
        let nx = px / canvasSize
        return -180.0 + nx * 360.0
    }

    static func latitudeForGameY(_ gameY: Double) -> Double {
        let py = (gameMaxY - gameY) * gameCoordScale
        let ny = py / canvasSize
        return atan(sinh(.pi * (1.0 - 2.0 * ny))) * 180.0 / .pi
    }
}
